### ISSUE TITLE
Neo GUI 2.5.2 crashes Win10_64  

### ISSUE THREAD

**Issue by Catweasel78** [neo-project/neo-gui#116]
after starting the gui windows start the werfault.exe

gui is crashing when old *.db3 database is found without warning or hit to change to new .json format

unmarshaled exception
Ausnahmeinformationen: Neo.IO.Data.LevelDB.LevelDBException
   bei Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr)
   bei Neo.IO.Data.LevelDB.DB.Open(System.String, Neo.IO.Data.LevelDB.Options)
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(System.String)
   bei Neo.Program.Main()

Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Neo.IO.Data.LevelDB.LevelDBException
   bei Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr)
   bei Neo.IO.Data.LevelDB.DB.Open(System.String, Neo.IO.Data.LevelDB.Options)
   bei Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(System.String)
   bei Neo.Program.Main()

**Comment by fabwa** [comment]
Please try to delete the Chain folder and reopen the application.

**Comment by jrsikors** [comment]
Similar issue with Windows 10 x64, but the problem ended up being because the config.json is a "new format".  So if you copy your old config.json file over with the new build, it auto crashes.

People with custom config.json's always have to go through extra steps each time a new GUI is released... either
A)  You need to copy your old config.json over
B)  You need to look at the format of the new config.json and figure out how to plop your values in the new format

I would eventually like to see something done where people like me don't have to do the extra steps !  I just want a custom directory for my Chain! :)

Love the NEO team though, keep up the good work !

This is the "new format"
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "Chain",
      "CertCache": "Certs"
    },
    "P2P": {
      "Port": 10333,
      "WsPort": 10334
    },
    "Urls": {
      "AddressUrl": "https://www.antchain.xyz/address/{0}",
      "AssetUrl": "https://www.antchain.xyz/asset/hash/{0}",
      "TransactionUrl": "https://www.antchain.xyz/tx/hash/{0}"
    }
  }
}


This is the "old format"
{
  "ApplicationConfiguration": {
    "DataDirectoryPath": "Chain",
    "CertCachePath": "Certs",
    "NodePort": 10333,
    "WsPort": 10334,
    "UriPrefix": [ "http://*:10332" ],
    "SslCert": "",
    "SslCertPassword": "",
    "Urls": {
      "AddressUrl": "https://www.antchain.xyz/address/{0}",
      "AssetUrl": "https://www.antchain.xyz/asset/hash/{0}",
      "TransactionUrl": "https://www.antchain.xyz/tx/hash/{0}"
    }
  }
}
