### ISSUE TITLE
NEO sent to NEO WALLET has not arrived.

### ISSUE THREAD

**Issue by episteme7905** [neo-project/neo-gui#142]
Transaction appears at Neotracker but does not appear in NEO WALLET - shows zero balance.

My receive address: AbTFuqir5bcmWdmbBWEBNtqnkpTCy5WeZB

How long should this transaction take?

When I search the address at Neotracker under the heading First transaction it states UNSPENT.
What does UNSPENT mean?

If the address can be seen in all the Block Explorers why doesn't it appear or show in my NEO-WALLET!?

Please help.

Many thanks and greetings from south korea
  
+) https://neotracker.io/address/AbTFuqir5bcmWdmbBWEBNtqnkpTCy5WeZB

**Comment by jrsikors** [comment]
When you open NEO-GUI.exe .. and load up your wallet ... are you sure you are fully sync'd?

For your wallet/transaction to be shown, you would at least need to see something like:
1,792,095/1,792,095/1,802,405

See https://github.com/neo-project/neo-gui/issues/141
for tips on how to speed up the sync if your sync is slow and you want to speed it up

**Comment by Yippyiyo** [comment]
Thank you for your reply. Wallet is fully syndcd. 

1803655 / 1803655

No NEO, No GAS , No Unclaimed GAS< No DBC.

**Comment by iR1gO** [comment]
Guys, need your help.
I've same problem. neotracker shows that i have 1 neo and some GAS as well. But in my NEO-GUI it's not shows. 
I'm fully sync'd. 
Height: 1723992/1723992/1723992. 

What could be a problem?

**Comment by jrsikors** [comment]
the latest block right this second is 1,806,811 (https://neotracker.io/browse/block/1)

So you are 80,000 blocks behind and not fully sync'd.

**Comment by jrsikors** [comment]
if your numbers aren't increasing ... i would suggest closing down and re-opening NEO-GUI.exe.  I always wait until I see at least 1 "Connected" before I load up my wallet.  In other words, don't open NEO-GUI.exe and immediately open your wallet.

It probably doesn't/shouldn't matter, but just personal preference

**Comment by iR1gO** [comment]
But why mine third number is still 172339. and how can i update that? Thx for help

**Comment by jrsikors** [comment]
close down NEO-GUI.exe and re-open, sometimes it gets stuck.

**Comment by Yippyiyo** [comment]
As long as you have your NEO address and your private key there is not a problem.
Go to neotracker.io and select "open wallet".

The choose "Private Key". And enter your WIF key.
That will open up and you will see your NEO, GAS etc.

Then uninstall existing desktop wallet. Install new neo-gui and create a new wallet database (different address).
Update the Blockchain. Then send the online NEO to your desktop wallet.

My numbers are:
0/1778240/1806903The first number 0 is new. That was not in previous Neo-Gui.
(What does that mean. Counts up then resets.)
Close your database and it may update more quickly.
I am doing this right now. 

(Found it in error was sniffing around NEOTRACKER ).

Good luck.

Try the NEO online wallet and let us know if it works.
BUT IT DOES CONCERN ME  BECAUSE ALL NEO-GUI DESKTOP WALLETS ARE ONLINE!!!!
IF YOU HAVE THE PRIVATE KEY!!!!

**Comment by jrsikors** [comment]
the first number is where your wallet is synced.
the second number is where your 'desktop/laptop' is synced
the third number is the latest block in the chain

But i essentially I had to do the same thing as you --- I went to NEON wallet temporarily though.

I basically sent all my coins to NEON wallet ... then deleted all my Chain and wallet file ... then i downloaded new NEO-GUI, downloaded bootstrap, let it sync, created new wallet, let that sync, then sent my coins back to NEO-GUI

**Comment by Yippyiyo** [comment]
jrsikors

Please understand that when you have a NEO-GUI wallet on your PC etc you automatically get an ONLINE wallet on neotracker.

I refused to put my stash online in the NEO (not NEON)  wallet at neotracker.io so I downloaded NEO-GUI and yet they are one and the same thing. Just go to neotracker and input your private wif key in open wallet.

VOILA there is your wallet. Both on your computer and online?

Is this unknown?

I was somewhat shocked to discover this, but I was also thrilled in that I could see that my NEO, Gas and DBC were still there. And as soon as my wallets syncs I will download down to my latest PC wallet.

And then find out how secure neo tracker wallet is?

I think a second layer and maybe third layer of protection is needed here.

I am in Australia. When I sell on coinspot.com.au I need my Google authenticator code and then I have to confirm the transaction by confirming the email they send me.

We will see more of 3 level protection soon.

**Comment by jrsikors** [comment]
Most cryptocurrency I've seen can be loaded into dozens of different wallets / places ... all you need is the private key.  Bitcoin is the same way and is the core of blockchain / cryptocurrency technology.  If you have the private key, you can load up your private key in ANY bitcoin wallet and your balance will be there .  Your public and private key are for the blockchain, it's not for any specific wallet.  You could also load your private key into the NEON wallet.

I personally wouldn't do that, as now you've loaded your private key into 3 different places, 3 potential places that could be 'hacked'.  I don't know neotracker.io, but it's listed on reddit so i imagine it's trusted.  But I typically only trust non-3rd-party stuff, which is why I use NEO-GUI.

NEO-GUI is not an 'exchange'.  You have your wallet, you encrypt it with a password, and you are done.  When you want to send your coins, you decrypt it with your password and send.

**Comment by Yippyiyo** [comment]
Thank you I did know that.

I will now insure that I only use the private key when an emergency.

And I will change my data files to ensure a virgin VIF key.

Six months ago (here)  I was trying to find 1 X Neo (#74) that was lost in the Blockchain and no-one here or at reddit could present me with the answer on how to recover it. Took months. I eventually recovered but it took me a long time. And yet the solution was so simple.

But NEO'ers had no idea!

Go to neotracker - open wallet etc and VOILA!

And yet today I recover 100 NEO in just over a day!

Knowledge I suppose.

Thank you very much for your assistance.

Greetings to you from Melbourne Australia.

**Comment by jrsikors** [comment]
Most important lesson , hopefully you and the other folks with the similar issue learned, is don't send your funds to a wallet that isn't fully sync'd :)

There's plenty of wallets around that don't require sync'ing like NEON ... and apparently neotracker.io (I've been telling people to go there but i didn't even realize you could load your wallet there).

But you always need to be careful with "3rd party wallets".  The only 'hacks' I've ever heard about in CryptoWorld are either:
  A)  3rd party wallets
  B)  Exchanges

With something like NEO-GUI, you and ONLY you have the private key... and thus it can never be stolen unless you do something wrong like lose it, your computer gets hacked and you have it written in a text file, etc.

Exchanges don't give you your private key, so you have no control over it.  The exchange could shut down, and you'd lose it.

Some 3rd party apps are poorly built and keep a copy of your private key on their servers.  So you have your private key, and they have your private key.

Anyways -- we are off topic now , glad your problem is resolved, cheers from Texas !

**Comment by Yippyiyo** [comment]
Cheers! It was a true pleasure!
:)

**Comment by afsoon-Gla** [comment]
hi there , i bought Neo from coinex and sent to Infinito wallet . it is not shown my balance but Neotracker shoed it.
what should i do?can i send it from online wallet of neotracker.io ?
