### ISSUE TITLE
Can No Longer Open Neo-Gui Application 

### ISSUE THREAD

**Issue by ericjredden** [neo-project/neo-gui#145]
I downloaded the Neo-Gui Application and created a wallet file .db3 and they worked fine for a while.  Now I can't open up either.  Please help.

Thanks,
Eric

**Comment by Yippyiyo** [comment]
What version of NEO-GUI do you have?
More info you can provide the better.
Operating system etc.
Do you have the private key?
If you have the private Key WIF see my post in 143.

The first thing that anyone should do is make a copy of the "private" stuff and keep it very secure..

Because without that private stuff you are rooted!!

**Comment by jrsikors** [comment]
More information definitely needed as Yippyiyo said... check out these 3 topics to see if any of these solutions work out for you:
#116 
#118 
#131

**Comment by Yippyiyo** [comment]
The NEO network is currently experiencing major problems.
Don't know whether it related to your issue.

https://twitter.com/neotrackerio?lang=en

**Comment by ericjredden** [comment]
I’m using Windows 7.  In my Ne0-Gui-Windows folder, I have a Neo-Gui.exe file that in the details says it’s version 2.0.6435.33609,  I last modified on 8/17/2017.  I used to click on this to open up and see my NEO.

I also have a wallet that is a separate file that ends in .db3.  When I try to open this file at least I get a message “Window can’t open this file: To open this file, Windows needs to know what program you want to use to open it.  Window can go online to look it up automatically, or you can manually select from a list of programs that are installed on your computer.”  I never received this message before when I created the wallet.

I’m concerned that if I try to download a new Neo-Gui.exe file that I lose all my NEO, or that my wallet won’t come up or something.  I’m not sure what to do.

**Comment by jrsikors** [comment]
You don't "open" the db3 file by double clicking it separately.  That is your wallet file.

You run neo-gui.exe ... then you go to Wallet -> Open Wallet and you open the db3 *within* the NEO-GUI.exe client.

**Comment by Yippyiyo** [comment]
Have you backed up your private keys? (HEX or WIF)
Did you backup your wallet .db3 file after receiving your stash of NEO?
How many .DB3  files do you have  Is that one or two?

If you have "private keys" see my other recent posts. 142, 143?

If you do not have privates, keep reading.
Download and install new neo-gui 2..3.X.
Do NOT install the 2.5 latest one. It does not use a .DB3 file.
https://github.com/neo-project/neo-gui/releases

Install to a different location. I install my NEO-GUI on USB stick/thumb drive . 
Once you have it installed choose create a New Wallet Database and point it an existing .db3 file/s.

Let us know if that works.

Backing up regularly is the only way to ensure you keep control of any of your Cryptos.

**Comment by ericjredden** [comment]
I don’t have the private key.  I have one .db3 that is my wallet and a test.db3 file I created.  

I will try to download the neo-GUI 2.3.5 onto my usb.

Sorry, how do I create a new wallet database and point it to my existing db3 file? 

I’m really careful because I dont want to loose all my neo.

**Comment by Yippyiyo** [comment]
Hi

Sorry I made an error. But not serious.

When you install the new NEO-GUI you will open the .db3 you used in your original setup.

So go to:
WALLET
OPEN WALLET DATABASE

In the dialogue box that pops up BROWSE to your .db3 file.

Now you are going to be way out of sync with Block Height numbers (bottom left), but don't worry about that at the moment.

What you are trying to do is recover your private key. That is the initial objective.

So when you open that .db3 file highlight the address and right click.

In the box 4th on the list is VIEW PRIVATE KEY. Copy every line in the new box.

What you need is the HEX or WIF keys.

Will look like this without the Xs and Zs
HEX:
XXXXXXc07XXX55fce7843d257XXXc714dfb5ed5aa7eXXXXXX6d2f6541fdXXXXX

WIF:
ZZZZZZZZZZKdNEHpVMtxmJYZZZZZZZZZZhqaFPBzACkXXXXXXXXX
Copy those into a text file and save them preferably on a USB stick.

Now head over to neotracker.io
and choose OPEN WALLET.
Enter your HEX or WIF and voila!
You will see your NEO there.

Good luck!
If you are successful post here for more info.

Keep us posted.
Now you may not be able to send out the neotracker wallet at the  moment because Neotracker.io wallet is having some send/receive issues.

**Comment by jrsikors** [comment]
any update eric?

**Comment by ericjredden** [comment]
Please confirm my steps are correct, I don’t want to lose all my NEO.  
1. I download Neo-GUI 2.3.x to my downloads and not the documents file I have the other downloaded version.  
2.  I move neo-GUI file from downloads to a USB?
3.  I move my .db3 file to usb?
4.  I open both the Neo-GUI and and .db3 and get the two codes (HEX and WIF) then save them .
5.  I go to neotracker.io, open wallet ?

Sorry, I’m very worried if I just download a new Neo-GUI that I will delete my neo. 

Please spell it out , or maybe I buy a new computer to download a Neo-2.3x and thenTry to open my .db3 on a new computer?

Thanks

**Comment by jrsikors** [comment]
Why are you trying to open your db3 file from your computer.  We've explained that...
step 1)  Open NEO-GUI.exe
step 2)  Go to Wallet -> Open Wallet Database
Step 3)  Select your DB3 file

![ss1](https://user-images.githubusercontent.com/31370541/35072692-451a59d4-fbab-11e7-982a-9f911611eb88.PNG)

![ss2](https://user-images.githubusercontent.com/31370541/35072719-662a043a-fbab-11e7-9b88-24906c395a77.PNG)

**Comment by jrsikors** [comment]
the second screenshot , you click on "Browse", and you find your DB3 file.. then your wallet is loaded.  

Make a backup of the db3 file before you do this just in case.

It doesn't matter if you are on NEO 2.3, 2.5, 2.5.2 ...  but I would stick with your current 2.3 for now.  If you 'upgrade' to NEO-GUI 2.5.2 , it will try to convert your db3 file to a .json file , which is fine, but you sound like you don't need to add another layer of confusion.

So -- get your wallet open with the steps and screenshots above.

**Comment by ericjredden** [comment]
Mission Accomplished.  I have my Hex and WIF private keys safely secured on a USG.  I also have my NEO available to send on Neotracker.io wallet and some gas available to claim.  This was very helpful, from now on I guess I will just use Neotracker.io because my numbers are alway out of sinc on my computer.

Where are you from/name or email?

Thanks,
Eric

**Comment by jrsikors** [comment]
There definitely seem to be some major sync issues going on with a lot of people.  The NEO-GUI.exe client is great, but the syncing has been an issue for a while now.  

My name is Jeff and I'm from Dallas, TX.  You can reach me at j_sikorsk@yahoo.com .  Good luck in your crypto investments !
