### ISSUE TITLE
2.6 is a major resource hog

### ISSUE THREAD

**Issue by gitbrook** [neo-project/neo-gui#172]
The new NEO-GUI version 2.6 is a major hog when syncing to the chain. I am running on a i7-6700 with 16GB DDR4, and running the application on a 250GB SSD with plenty of space. MY CPU was pegged for hours and I couldn't run any other serious software. It did fix my GAS claiming issue. I hadn't been able to claim gas in weeks, and this wallet version fixed that.

**Comment by jrsikors** [comment]
+1 for this.  

NEO-GUI.exe seems to trigger "Local Security Authority Process" 
   -CNG Key Isolation
   -Credential Manager
   -Security Accounts Manager

to run out of control as well.

Those 2 processes (NEO-GUI.exe and Local Security Authority Process) will suck up 100% CPU during a long sync.

**Comment by bumbak** [comment]
Same here, NEO GUI 2.6.0 + "Local Security Authority Process" eating up my resources.. :S

**Comment by jrsikors** [comment]
For the devs -

This was true in prior versions as well ... but it's more noticeable in 2.6.0 because 2.6.0 seems to be forcing a re-download of the whole blockchain.

Once you are sync'd -- even though the processes still occasionally eat up a lot of CPU , it's less noticeable because it's not constant.

But yeah -- to duplicate -- just do a fresh download 2.6.0 NEO-GUI ... fresh / blank data directory ... and check your CPU/memory after about 20 minutes.  More than likely you will see what we are talking about.

**Comment by stephenhodgkiss** [comment]
Same issue here, using the latest NEO-GUI version that I downloaded a few days ago, After downloading the snapshot, moving it to the correct folder and starting it up, it soon took up all my machine.

AMD QUAD CORE PROCESSOR A10-9620P
8GB DDR4 RAM
128GB SSD
WINDOWS 10

It had between 50-75% of the CPU and at times, 5GB RAM.

**Comment by stephenhodgkiss** [comment]
There doesn't seem to be any response from the developers on this issue. I am still struggling to get the GUI to sync.

**Comment by jrsikors** [comment]
I would say there isn't a response -- but I know @erikzhang watches this page and would bet a lot of money he relays to the team about all the issues.  He usually responds if you ask him directly ..

like hey @erikzhang can you please put a new chain.acc.zip up that is closer to full sync and let us know when it's there :smile: 

I do think the only issue at hand is the stuck blocks due to node issues -- 
-- and the only solution is to get a chain.acc.zip that gets past those blocks --
-- and the only way to get an updated chain.acc.zip is from the NEO team :smile:

**Comment by Ashuaidehao** [comment]
Hi @gitbrook ,  is this problem still happen? Did you try to run it using the last version?

**Comment by Ashuaidehao** [comment]
Hi @gitbrook，we're planning to close this issue due to inactivity.
If you still have problems, please reopen this issue or create a new one.
@lock9 can you help to close this ,thanks!
