### ISSUE TITLE
Neo Deposited to a second address

### ISSUE THREAD

**Issue by MattAliceSprings** [neo-project/neo-gui#189]
Hi

I sent 18 NEO from an exchange to my address 17 Went to my address and 1 went to a different address that has thousands of NEO in it.
Can any one explain this to me, I lost Five NEO months ago like this.
Help please

6bfc11715693ed3467c2773dcf95a7eec249a2abff1ba153e2bd10a8ecc4a874 - Contract
1,919,303 - Block
AUv6oq7nbc3k4gscf1aCcrCQEVc2RgMb9J -18 NEO -KUcoin address
AK9dr2JFE5oazrsUtLdZW4Txb923hQRzWB 17 - My address
AYMsx8an5H7F8SfAw2hMZkhtcUBe74eP1L 1 - Address with Thousands

**Comment by jrsikors** [comment]
What exchange are you using?
What wallet are you using to send your funds to?

It almost looks like the Exchange is the problem here and you need to take it up with them.

If you look at the last 5 transactions on:
https://neotracker.io/address/AYMsx8an5H7F8SfAw2hMZkhtcUBe74eP1L

it seems like every time someone is making a transfer, of GAS or NEO, AYMsx8an5H7F8SfAw2hMZkhtcUBe74eP1L seems to be taking a "fee".

So either the exchange is hacked, your wallet source is hacked, your exchange is charging you a crazy fee. or the exchange isn't handling NEO transactions properly.

**Comment by jrsikors** [comment]
If you look at this transaction:
https://neotracker.io/tx/d8b8f27e84032f06ddb59b49946365ffc7c43f8f98d85ef5bbd59a6dd23b0ab0

1 neo was sent FROM the mystery address to another address.  So the good news is it seems to be active and not a black hole.

**Comment by jrsikors** [comment]
any update?
What exchange are you using?
What wallet are you using to send your funds to?

**Comment by MattAliceSprings** [comment]
Ok

What it was is the exchange sent out two transactions on the one block, so there was no problem with the NEO chain, just me misinterpreting the data in the block explorer. I FKD up.

Thanks
Matt

**Comment by jrsikors** [comment]
Good to hear your funds are safe !  No worries !

@erikzhang @MattAliceSprings  you can close this issue up
