### ISSUE TITLE
can't claim gas

### ISSUE THREAD

**Issue by viraladmin** [neo-project/neo-gui#211]
Trying to claim my GAS. I have gas. Can't claim it. When I try sending neo to myself to be able to claim, the transaction indefinitely sits doing  nothing. When I restart the wallet, the transaction no longer appears. 

Currently I tried again around an hour ago. txid 0xfcfcb0e6e1ff69b39a3bf9eb76d1e42f4f3c615c69e62dddf4a986339c30a005 just sits unconfirmed. 

NEO tracker claims page not found when looking up txid. 

Can't claim my GAS at all from neo-gui wallet. Sending to myself doesn't seem to work, 

This is the version shows NEO version 2.5.6557 which I believe is the latest.

blocks show across the board: 2000190/2000190/2000190

**Comment by jrsikors** [comment]
You are not on the latest version... and you HAVE to be or you will experience weird problems (because you aren't really syncd)

https://github.com/neo-project/neo-gui/releases

https://github.com/neo-project/neo-gui/releases/latest

https://neo.org/download

Be sure to read through:
http://docs.neo.org/en-us/node/gui.html

to help speed up the sync process for your new 2.6 client.  You will basically need to do a full-sync again, but the document guide will help speed it up.

**Comment by jrsikors** [comment]
and check this out too:
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/

**Comment by viraladmin** [comment]
ty for the help got it all sorted :)

**Comment by jrsikors** [comment]
no prob .. @viraladmin or @erikzhang  please close issue!
