### ISSUE TITLE
You need to add a Debug Window [like BTC, LTC, etc.]

### ISSUE THREAD

**Issue by katzky** [neo-project/neo-gui#219]
Currently there is no way to see what nodes are connected to your node. My client is stuck and can't get new blocks because all the nodes I'm connected to are probably also stuck at block 2,022,689.

**Comment by jrsikors** [comment]
Someone posted this link in one of the last few topics:
http://monitor.cityofzion.io/

I dont think there are any Nodes having issues.

I think you are just in a situation where you need to start over again, COMPLETELY FRESH.  I listed steps in #207  , but basically:

So I just did this
step 1) Downloaded the latest https://github.com/neo-project/neo-gui/releases/latest
step 2) Downloaded the chain.acc.zip from http://static.neo.org/client/chain.acc.zip
Step 3) Unzipped it to c:\NEO26 (or wherever)
Step 4) COPIED DIDNT UNZIP the chain.acc.zip to C:\neo26
Step 5) Launched neo-gui from c:\neo26

Within 10 minutes of opening ... my 2nd and 3rd numbers are already at 1.25 million each ... and i have 0 'connections' ... which means the chain.acc.zip is doing its job.

after about an hour, it looks like it stopped 'speed syncing' at around 0 / 1.8 million / 1.8 million ... and the remaining 200,000 blocks blocks will need to sync normally .. which will probably be a while.

After 24 hours I was sync'd up.

I have not opened my wallet file yet -- nor will I until I am sync'd

So -- I think you need to pay very close attention to my steps and do them exactly. You aren't doing something right... either you are:
A) Not on the latest 2.6 NEO GUI, my step 1 will cover that
B) Have a bad chain.acc.zip, my step 2 should cover that
C) Have data in your chain folder already which is preventing the chain.acc.zip from working properly.. my step 3 will cover that (will create a brand new fresh directory for Chain folder)
D) Are unzipping the chain.acc.zip ... my step 3 will cover that

**Comment by jrsikors** [comment]
follow those instructions to the letter.. don't cheat or think you know better or think I typo'd something :smile: .. i didnt ... that is 100% correct and will get you from 0/0/0 to 0 / 1.8 mil / 1.8 mil

Make sure it's a different directory so you have a fresh everything ... no existing Chain folder .. no chain.acc or chain.acc.zip

The simplest is just to unzip NEO 2.6 into a new directory
if you were using:
C:\NEO26
Use:
C:\NEO26NEW

completely fresh start , follow those instructions, and I promise it will work fine

**Comment by jrsikors** [comment]
Basically -- I think there are 3 problems:
1)  Everyone was forced to re-sync on 2.6 from 0/0/0

2)  The "bootstrap" process to sync is a new concept and most people didn't read the instructions clearly (myself included, i am guilty).  When people see a zip file, they want to unzip it.  The NEO team's instructions CLEARLY said don't unzip it.. but from what I gathered on these posts, most people overlooked that part in the instructions.  When I download a ZIP file, I want to unzip it... and I think most people think like this too :smile: 

3)  The nodes issues they started having a couple weeks ago exacerbated an already frustrating re-sync process

I totally agree this process has been extremely frustrating when they upgraded to 2.6 and forced everyone to resync .  Hopefully Erik and the NEO team saw all the posts and are coming up with some enhancements.

I'm guessing your problem isn't node related (because there are no problems related to nodes) -- but more of a "corrupt database chain"... and starting from scratch again is your best bet.

**Comment by katzky** [comment]
Yeah I have already done all the steps as outlined in your comments. The client keeps hanging and needs to be restarted every 50k - 100k blocks. [The client indicates "(Not Responding)"]

I was able to quickly sync via the bootstrap on a couple of occasions but this time it just keeps hanging.

**Comment by JKAbrams** [comment]
I had the same problem and I found that Neo-GUI does not work on 32 bit Windows 7 in a virtual machine. It reaches 1.6GB memory usage then it crashes, which takes about 2.5 minutes on my machine. The amount of memory actually available to the machine did not matter, except for when I set it to 1.2GB total memory, it did not crash anymore but instead ran horribly slow.
I found no solution to the problem, but I switched to a 64 bit version of windows 7 and now it only crashes occasionally for some other reason.
I assume development is done on 64 bit systems and 32 bit is not tested.

**Comment by nachtmens** [comment]
After a long time I decided to pay attention  to my stacked Neo's.
So I downloaded the NEO-GUI 2.7. Indeed I did run into the problems as described in jrsikors comments
refering to A),B), C) and D). After a (indeed) frustrating proces I got the NEO-Gui syncing.
At the first attempt got stuck around about block height 3203303 or something close. At the second 
attempt got stuck at Block height 3773043.

Then did a new fresh start with NEO-GUI 2.10.7167.31939, and now I seem be stuck at 
Block height 3773043 again. "seem" because the synchronized wallet blockchain height is 
still catching up. But the wallet does not receive new blocks anymore since more than 8 hours.

A) I used the latest NEO-GUI.exe
B) Before installing, deleted the former NEO-GUI map, so completely fresh.
C) I made sure that I used the latest ImportBlocks Plugin.
D) I made sure that I used the latest Full Offline Package.
E) Did not unzip chain.acc.zip .
F) Did not put chain.acc.zip into the Chain_xxxx Folder, but in the NEO-GUI folder.

Is it maybe RAM memory related? I have 16MB installed.
