### ISSUE TITLE
New NEO gui.  Is there a Wallet .db3 file that I can download to catch up?

### ISSUE THREAD

**Issue by DeepM1** [neo-project/neo-gui#32]
I have downloaded the new NEO gui on my PC Windows 10.  It has been over 20 hours now and I have only 1414935/1239872.   The download freezes...continually "waiting for new block", but does nothing.  I have found that I have to exit  and restart the wallet program.  After this is done, the download restarts.  However, the download shortly thereafter freezes again.  Is there a file I can download or can anybody help in another way?  Thanks.

**Comment by greenriverneo** [comment]
Same here, I don't have a .db3 file like the antshares gui wallet.

**Comment by uberlance** [comment]
If you previously had been using the AntSharesCore gui, you can speed up sync by copying the Chain folder from the root of the AntSharesCore directory to the root of your new Neo directory.  The client must be shutdown when you do this.  When you launch neo-gui, the chain should already be up to the height it was the last time you ran AntSharesUI.exe and only have to sync blocks since then.

As for the db3 file, if you already had one you should be able to simply open it up your prior .db3 file with neo-gui and your SystemShares (NEO) will be there.

**Comment by DeepM1** [comment]
What if I never had an AntShares gui before? I did not. Then what world I do to speed up the process?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by uberlance** [comment]
Download https://www.antshares.org/client/chain.acc.zip

Unzip in the neo directory and then launch neo-gui

**Comment by DeepM1** [comment]
There we go...Thx!!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by erikzhang** [comment]
it seems the problem has been resolved. I will close this issue.

**Comment by greenriverneo** [comment]
Thanks guys.  Yes, new .db3 installed.  I imported my antshares wallet into the new wallet, so now I have 2 wallet addresses.  Can I delete the wallet address I just created on the new database and keep only my trusty old one from the antshares gui?  Or is that way too much of a pain and I just don't need to use the new wallet address now that the old one is linked.  :D   Thanks again!

**Comment by erikzhang** [comment]
Make sure that there is no asset in the address you want to delete. Otherwise, there is no chance to recover them. You must to be very careful.

**Comment by greenriverneo** [comment]
I am not going to mess with it.   The Oracle told me I am not the One.  :(   ;D

**Comment by skhameneh** [comment]
New URL: https://neo.org/client/chain.acc.zip
