### ISSUE TITLE
GUI not loading (windows)

### ISSUE THREAD

**Issue by dynomonkey** [neo-project/neo-gui#69]
I downloaded the windows GUI a few days ago. It was working fine at first then I tried to add the chain.acc to the folder to speed up the sync.  Since that it has not worked. I have tried to remove chain.acc and also I have reinstalled and it's still not working.  When I click the executable nothing happens, I have check the task manager and it's not running in the background. There is no error message

**Comment by EagleEyes81** [comment]
I had exactly same problem since last month. Two times GUI has crashed without any known reason. Both times it was successfully up and running with all the nodes synced and I can see all the features and my NEO balance BUT then suddenly it doesn't open at all. Installed again and after few days it happened again in the night.  The program was open and was syncing the nodes while I went sleep, the laptop went to sleep or turned off because of low battery may be and then cannot open the GUI again and there is no error and no response. Not even running on the background processes.
There is an error file created which is showing the following text, I believe is related to corruption:

Neo.Implementations.Blockchains.LevelDB.LevelDBException
Corruption: not an sstable (bad magic number)
   at Neo.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.Implementations.Blockchains.LevelDB.DB.Get(ReadOptions options, Slice key)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in C:\Users\erik\Documents\Visual Studio 2017\Projects\neo-gui\neo-gui\Program.cs:line 121

**Comment by gvibrations** [comment]
Same problem ... different error:
Neo.Implementations.Blockchains.LevelDB.LevelDBException
Corruption: CURRENT file does not end with newline
   at Neo.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.Implementations.Blockchains.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() #

Is anyone addressing this? How can I get to my wallet? If I reinstall and copy my walled.db to the new directory, will I be fine?

**Comment by erikzhang** [comment]
Remove the Chain directory and try again.

**Comment by moratar** [comment]
**Delete all files that are inside directory chain. You will need to synchronize your blockchain again. Wallet will be ok.**
This is not a fix, but a workaround.

This bug sometimes happens when your computer crashes while blocks from blockchain are updated.
Or when you force shutdown, without closing wallet-app first.
