### ISSUE TITLE
HELP!  NEO-GUI crashes when attempting to open wallet file, disk I/O error

### ISSUE THREAD

**Issue by user00101** [neo-project/neo-gui#93]
Hello,

I am getting an error when I  try and open my wallet file.  I was able to create the wallet and move 2 neo to the address and the chain was updating fine but now when I try to log into the wallet file it crashes on me, as seen in the attached picture.  Any assitance would be greatly appreciated.
![capture](https://user-images.githubusercontent.com/33013843/31870379-a8918c7c-b77b-11e7-8b09-281a837d5c1e.JPG)

**Comment by bellua** [comment]
i had problems bec of my computers user name. had the letter è in my username, and both neo and electrum didnt like that(after a restart of my computer it didn't want to open the wallets, so made a new one without anny of the wierd letters and the problem was gone. it might not be the same problem at all, but it fixed it for me, so sharing it just in case :) greetings from norway ^,^

**Comment by user00101** [comment]
bellua,

Greetings!  That does not seem to be my issue but I do appreciate the tip.  

Regards

**Comment by user00101** [comment]
Bump :)

**Comment by erikzhang** [comment]
Can you provide more information in details?
